name: vitor-portfolio 

services:
  portfoliofront:
    build:
      context: ./
      target: production 
    container_name: portfoliofrontend
    restart: unless-stopped
    networks:
      - caddy_net 
    # env_file: client/.env
networks:
  caddy_net:
    external: true

